name: 'Build Chainlink and Publish'

on:
  # Mimics old circleci behaviour
  push:
    tags:
      - 'v*'
    branches:
      - master
      - develop
      - 'release/*'

jobs:
  build-sign-publish-chainlink:
    permissions:
      id-token: write # This is for OIDC integration with AWS role assumption
      contents: read  # This is required for actions/checkout@v2
    runs-on: ubuntu-20.04
    environment: build-publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Build, sign and publish chainlink image
        uses: ./.github/actions/build-sign-publish-chainlink
        with:
          publish: true
          image-name: chainlink
          aws-role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-role-duration-seconds: ${{ secrets.AWS_ROLE_DURATION_SECONDS }}
          aws-region: ${{ secrets.AWS_REGION }}
          sign-images: true
          verify-signature: true
